In [2]:
import numpy as np

In [38]:
# numpy arrays are homogenous we can store only single type of values

arr1 = np.array([1,2,3,4,5])
print(arr1, " " ,arr1.dtype, " " ,arr1.size , " ", arr1.shape , " " , arr1.ndim)

arr2 = np.array([1,2,3,4,5,"string"])
print(arr2,arr2.dtype)

[1 2 3 4 5]   int64   5   (5,)   1
['1' '2' '3' '4' '5' 'string'] <U21


In [ ]:
arr2d = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2d , arr2d.dtype)

arr2d = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2d , arr2d.shape ," ", arr2d.ndim)

#ndim is the no of dimensions

[[1 2 3]
 [3 4 5]
 [5 6 7]] int64
[[1 2 3]
 [3 4 5]
 [5 6 7]] (3, 3)   2


In [28]:
#creating numpy array from scratch

arr = np.zeros((2,3))
print(arr , arr.shape)

arr1 = np.zeros((3,3),dtype='<U21')
print(arr1 , arr1.shape)


arr2 = np.ones((2,3))
print(arr2 , arr2.shape)

arr2 = np.full((2,3),"hello")
print(arr2 , arr2.shape)

#--------------------------------

arr2 = np.eye((2))
print(arr2 , arr2.shape)
#it print the identity matrix

#--------------------------------
arr3 = np.arange(2)
#it work like a python range function (start , end , incriment)
print(arr3 , arr3.shape)

arr4 = np.arange(1,5)
print(arr4 , arr4.shape)

arr4 = np.arange(1,10,2)
print(arr4 , arr4.shape)

#--------------------------------

arr5 = np.linspace(0,100,5) #create evenly spaced elements (start , end , no of elements in arrays)
print(arr5 , arr5.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[['' '' '']
 ['' '' '']
 ['' '' '']] (3, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[['hello' 'hello' 'hello']
 ['hello' 'hello' 'hello']] (2, 3)
[[1. 0.]
 [0. 1.]] (2, 2)
[0 1] (2,)
[1 2 3 4] (4,)
[1 3 5 7 9] (5,)
[  0.  25.  50.  75. 100.] (5,)


In [37]:
#typecasting
arr = np.ones((2,3))
print(arr, arr.dtype)

print("--------------")

string_arr = arr.astype(np.str_)
print(string_arr , string_arr.dtype)

print("--------------")

int_arr = arr.astype(np.int64)
print(int_arr , int_arr.dtype)

[[1. 1. 1.]
 [1. 1. 1.]] float64
--------------
[['1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0']] <U32
--------------
[[1 1 1]
 [1 1 1]] int64


In [ ]:
#-=============[ Opertaions in arrays ]==============

# 1.reshaping the array

arr = np.array([[1,2,3],[3,4,5]])
print(arr , arr.shape)

print()

reshaped_arr = arr.reshape((3,2))
print(reshaped_arr , reshaped_arr.shape)

print()

flatten_arr = arr.flatten() #convert the multi dimension array into 1 dimension
print(flatten_arr , flatten_arr.shape)

[[1 2 3]
 [3 4 5]
 [5 6 7]] (3, 3)

[[1 2 3]
 [3 4 5]
 [5 6 7]] (3, 3)

[1 2 3 3 4 5 5 6 7] (9,)


In [49]:
# 2.indexing : accesing elements in array

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[3])

print()

# fancy indexing
idx = [0,3,5]
print(arr[idx])

print()

# boolean indexing : we can filter values based on some condition
print(arr[arr>2])
print(arr[arr%2==0])

4

[1 4 6]

[3 4 5 6 7 8]
[2 4 6 8]


In [ ]:
# 3.slicing 
#syntax : (start , end , step)

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::])
print(arr[1::2])
print(arr[0:5:])
print(arr[0:9:2])
#There is no index 8 or 9, but slicing simply stops when it reaches the end of the array. It does not raise an IndexError.

# in python list slicing create a copy which take extra time and memory both 
# in numpy array slicing it create a view which is basically the original values it do not take any new memory
# so means if we do some updation or changes then it reflect in the original one also e.g
print()
arr = np.array([1,2,3,4,5,6,7,8])
sub_arr = arr[1:4]
print(sub_arr)

sub_arr[0] = 20
print(sub_arr)
print(arr)

# Now what if we actually want a copy of array then we use .copy() function and then then changes do not reflect to the original one array e.g

print()
arr = np.array([1,2,3,4,5,6,7,8])
sub_arr = arr[1:4].copy()
print(sub_arr)

sub_arr[0] = 30
print(sub_arr)
print(arr)




[1 2 3 4 5 6 7 8]
[2 4 6 8]
[1 2 3 4 5]
[1 3 5 7]

[2 3 4]
[20  3  4]
[ 1 20  3  4  5  6  7  8]

[2 3 4]
[30  3  4]
[1 2 3 4 5 6 7 8]
