In [ ]:
#=============Axes============

# For a 2D array:

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Shape = (3, 3)

# Axis 0 (vertical ↓)
# - Moves down each column
# - Collapses rows
# - Keeps columns

# Example:
# arr.sum(axis=0)
# = [12 15 18]

# Axis 1 (horizontal →)
# - Moves across each row
# - Collapses columns
# - Keeps rows

# Example:
# arr.sum(axis=1)
# = [6 15 24]

# #Golden rule:
# Axis = the dimension NumPy operates along.

# When you use axis=k,
# NumPy reduces (collapses) that axis and keeps the remaining axes.


In [1]:
import numpy as np

In [ ]:
a = np.array([10, 20, 30, 40])

print(a ," " , a.shape) #has only one axis

[10 20 30 40]   (4,)


In [ ]:
arr = np.array([
    [1,2,3,4],
    [4,5,6,5],
    [7,8,9,6]
])

print(arr ," ",arr.shape) 
print(arr.sum())
result = arr.sum(axis=0)

print(result)                    # [12 15 18 15]
print(result.shape) 
#it take sum for every row in vertical directions and axis = 0 collapse the first dimension in shape of array eg before dimension of array is (3,4) and now it become (4,)

result1 = arr.sum(axis=1) #it collapses the second dimension so now for this shape become (3,)
print(result1)
print(result1.shape)

print("-"*10) 
print(arr.mean(axis=1))

print("-"*10) 
print(arr.max(axis=0)) #Largest in every column. beacuse it works verically

print("-"*10) 
print(arr.max(axis=1)) #Largest in every row beacuse it works horizontally

print("-"*10) 
print(arr.argmax(axis=0)) #basically it see vertically in every coloumn one by one and return the index of greater element in that coloumn

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 6]]   (3, 4)
60
[12 15 18 15]
(4,)
[10 20 30]
(3,)
----------
[2.5 5.  7.5]
----------
[7 8 9 6]
----------
[4 6 9]
----------
[2 2 2 2]


In [ ]:
#3d array and we can also make multidimensional arrays

a = np.arange(24).reshape(2,3,4)

print(a)
print(a.shape)

#Shape Rule:
# Axis 0 → 2
# Axis 1 → 3
# Axis 2 → 4

# Axis0 = Blocks
# Axis1 = Rows
# Axis2 = Columns

# Axis 0
# Block 0

# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Block 1

# [[12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [25]:
# ======================Vectorization===================

# Definition:
# Vectorization means performing operations on an entire NumPy array at once, without writing explicit Python loops.

arr = np.array([1,2,3,4,6,7])

print(arr**2)
print(arr*5)
print(arr>5)
print(arr[arr>5])
print(np.sqrt(arr))

arr1 = np.array([3,4,5,6,7,8])
print(arr+arr1)

[ 1  4  9 16 36 49]
[ 5 10 15 20 30 35]
[False False False False  True  True]
[6 7]
[1.         1.41421356 1.73205081 2.         2.44948974 2.64575131]
[ 4  6  8 10 13 15]


In [ ]:
#broadcasting
#Normalization