In [2]:
import numpy as np

In [4]:
# What is Normalization?

# Normalization means scaling data into a different range without changing the relationship between values.


data = np.array([10, 20, 30, 40, 50])

print(data)

# 1. Min-Max Normalization:
# # fORMULA : 
#     (X - Xmin)/(Xmax - Xmin)

import numpy as np

data = np.array([10, 20, 30, 40, 50])

minimum = np.min(data)
maximum = np.max(data)

print("Minimum:", minimum)
print("Maximum:", maximum)

normalized = (data - minimum) / (maximum - minimum)
print(normalized)

[10 20 30 40 50]
Minimum: 10
Maximum: 50
[0.   0.25 0.5  0.75 1.  ]


In [5]:
# Mean Normalization

# # Formula:
# (X - Mean)/(Xmax - Xmin)

data = np.array([10,20,30,40,50])

mean = np.mean(data)

normalized = (data - mean) / (np.max(data)-np.min(data))

print(normalized)

[-0.5  -0.25  0.    0.25  0.5 ]


In [7]:
# Z-Score Normalization (Standardization)
# Formula:
#     (x−μ)/σ
# Where
    # μ = mean
    # σ = standard deviation


data = np.array([10,20,30,40,50])

mean = np.mean(data)
std = np.std(data)

print(mean)
print(std)

z = (data - mean) / std

print(z)

30.0
14.142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [12]:
# Normalize a Matrix Column-wise

data = np.array([
    [10,100],
    [20,200],
    [30,300],
    [40,400]
])

print(data)
print()

minimum = np.min(data, axis=0)
maximum = np.max(data, axis=0)

print(minimum)
print()
print(maximum)
print()

normalized = (data - minimum) / (maximum - minimum)

print(normalized)

[[ 10 100]
 [ 20 200]
 [ 30 300]
 [ 40 400]]

[ 10 100]

[ 40 400]

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


In [14]:
# Normalize Row-wise
data = np.array([
    [1,2],
    [3,4],
    [5,6]
])

row_min = np.min(data, axis=1, keepdims=True)
row_max = np.max(data, axis=1, keepdims=True)

print(row_max)
print()
print(row_min)
print()
normalized = (data-row_min)/(row_max-row_min)

print(normalized)

[[2]
 [4]
 [6]]

[[1]
 [3]
 [5]]

[[0. 1.]
 [0. 1.]
 [0. 1.]]
