In [1]:
import numpy as np

In [5]:
#Broadcasting

# Broadcasting with a Scalar

a = np.array([1, 2, 3, 4])
print(a)

print(a + 10)

[1 2 3 4]
[11 12 13 14]


In [6]:
# Array + Array (Same Shape)

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a+b)

[11 22 33]


In [ ]:
# Different Shapes

a = np.array([[1],
              [2],
              [3]]) 

b = np.array([10,20,30])

#here a has shape (3,1) and b has shape (1,3) when we add a and b then a expand horizontally and b expand vertically and they become 
# a expands horizontally

# [[1 1 1]
#  [2 2 2]
#  [3 3 3]]

# b expands vertically

# [[10 20 30]
#  [10 20 30]
#  [10 20 30]]

print("a")
print(a)

print()

print("b")
print(b)

print()

print("Result")
print(a+b)

a
[[1]
 [2]
 [3]]

b
[10 20 30]

Result
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# A simple rule to remember

# When comparing two shapes:

# Start from the rightmost dimension.
# For every pair of dimensions, they must be equal or one of them must be 1.
# If one array has fewer dimensions, imagine it has leading 1s.
# For example:

# (3, 2)
# (2,)

# is treated as:

# (3, 2)
# (1, 2)

# which is why broadcasting works in that case.

In [ ]:
# if the one has multi dimensions and the other one is single dimesnion firstly is should equal to the last one dimesnion of first and then you can add leading ones and then broadcasting is valid means (2,3,4,5) and (5) valid but (2,3,4,5) and (3) not valid
# Suppose:

# A.shape = (2, 3, 4, 5)
# Case 1: B.shape = (5,)

# NumPy first pads the smaller shape with leading 1s:

# A: (2, 3, 4, 5)
# B: (1, 1, 1, 5)

# This is valid

# Case 2: B.shape = (3,)

# Pad with leading 1s:

# A: (2, 3, 4, 5)
# B: (1, 1, 1, 3)
# This is not valid

In [8]:
a = np.ones((2,3))

print(a)

print()
b = np.array([10,20,30])

print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[11. 21. 31.]
 [11. 21. 31.]]


In [10]:
# Three-Dimensional Example

a = np.ones((2,3,4))

b = np.array([1,2,3,4])

print(a.shape)
print(b.shape)
print()

print(a+b)
print((a+b).shape)

(2, 3, 4)
(4,)

[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]
(2, 3, 4)


In [12]:
#Practice

a = np.array([1,2,3])
print(a + 5)

[6 7 8]


In [13]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([10,20])

print(a+b)

[[11 21]
 [12 22]
 [13 23]]


In [14]:
a = np.ones((3,4))
b = np.array([1,2,3,4])

print(a+b)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [15]:
a = np.ones((2,1))
b = np.array([[10,20,30]])

print(a+b)

[[11. 21. 31.]
 [11. 21. 31.]]


In [16]:
a = np.array([[1,2],
              [3,4]])

b = np.array([10,20])

print(a+b)

[[11 22]
 [13 24]]
